# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ff3e03970e89ea2fb947b133ef64562c4f6bf5245d0f01287eff84f689e9d1e76f4313fba251b98c07fee0b3ee6be2cd149097ffd3aac59bf2dadd957f8a3ea

test:
  secret_key_base: e927b75c6d813a63a3066c528319191725bb0927a8340ad326319c91acfeeb9df30536f4d671ccc464303e8895bf3a5103a0d9722ae50f00103502a0a0694213

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
